import SwiftUI
import OpenMasjidCore

@main struct OpenMasjidApp: App { @StateObject private var model = AppModel(); var body: some Scene { WindowGroup { RootView().environmentObject(model) } } }

@MainActor final class AppModel: ObservableObject {
    @Published var site: Site?; @Published var status: SiteLoadState = .loading; @Published var selectedCampusID: String? { didSet { selection.id = selectedCampusID } }; @Published var websiteBase = "https://example.org"
    private let store=SiteStore(); private let selection=CampusSelection()
    init() { selectedCampusID=selection.id; if let url=Bundle.main.url(forResource:"demo-site",withExtension:"json"),let data=try? Data(contentsOf:url),let demo=try? JSONDecoder().decode(Site.self,from:data) { site=demo; if selectedCampusID == nil {selectedCampusID=demo.campuses.first?.id} }; status=site.map{.loaded($0,stale:true)} ?? .loading }
    var campus: Campus? { site?.campuses.first{$0.id==selectedCampusID} ?? site?.campuses.first }
    func refresh() { guard let url=URL(string:websiteBase), let config=try? SiteConfiguration(websiteBase:url) else { status = .failed("Enter an HTTPS website base URL."); return }; store.load(configuration:config) { [weak self] state in guard let self else{return}; self.status=state; if case .loaded(let s,_)=state {self.site=s;if self.selectedCampusID == nil || !s.campuses.contains(where:{$0.id==self.selectedCampusID}) {self.selectedCampusID=s.campuses.first?.id} } } }
}

struct RootView: View { @EnvironmentObject var model:AppModel; var body:some View { TabView { NavigationStack { HomeView() }.tabItem{Label("Today",systemImage:"sun.max.fill")}; NavigationStack { EventsView() }.tabItem{Label("Events",systemImage:"calendar")}; NavigationStack { AnnouncementsView() }.tabItem{Label("Updates",systemImage:"bell")}; NavigationStack { SettingsView() }.tabItem{Label("Settings",systemImage:"gear")}}.tint(.forest).background(Color.ivory) } }
struct Shell<Content:View>: View { let title:String; @ViewBuilder let content:Content; var body:some View { ScrollView { VStack(alignment:.leading,spacing:20){ Text(title).font(.system(.largeTitle,design:.serif).weight(.bold)).foregroundStyle(.forest); content }.padding(20) }.background(Color.ivory.ignoresSafeArea()).toolbarBackground(Color.ivory,for:.navigationBar) } }
struct CampusPicker: View { @EnvironmentObject var model:AppModel; var body:some View { if let campuses=model.site?.campuses { Picker("Campus",selection:Binding(get:{model.selectedCampusID ?? campuses.first!.id},set:{model.selectedCampusID=$0})){ForEach(campuses){Text($0.name).tag($0.id)}}.pickerStyle(.menu).tint(.brass) } } }
struct HomeView: View { @EnvironmentObject var model:AppModel; var body:some View { Shell(title:"Today") { CampusPicker(); if case .loaded(_,let stale)=model.status,stale { Notice(text:"Showing your last saved schedule. Pull to refresh when online.",icon:"icloud.slash") }; if let campus=model.campus { PrayerCard(campus:campus); ScheduleCard(campus:campus); ContactCard(campus:campus) } else { ProgressView("Loading schedule…") } }.refreshable{model.refresh()} } }
struct PrayerCard: View { let campus:Campus; var body:some View { VStack(alignment:.leading,spacing:12){ Text(campus.name.uppercased()).font(.caption.weight(.bold)).tracking(1.5).foregroundStyle(.brass); Text(nextPrayer()).font(.system(.title2,design:.serif).weight(.semibold)).foregroundStyle(.forest); HStack{ForEach([("Fajr",campus.iqamah.fajr),("Dhuhr",campus.iqamah.dhuhr),("Asr",campus.iqamah.asr),("Maghrib",campus.iqamah.maghrib),("Isha",campus.iqamah.isha)],id:\.0){ item in VStack(alignment:.leading){Text(item.0).font(.caption).foregroundStyle(.secondary);Text(item.1).font(.headline.monospacedDigit())}}}.frame(maxWidth:.infinity,alignment:.leading) }.padding(20).background(RoundedRectangle(cornerRadius:24).fill(Color.forest)).foregroundStyle(.white).overlay(alignment:.topTrailing){Circle().stroke(Color.brass.opacity(0.7),lineWidth:2).frame(width:110,height:110).offset(x:25,y:-35)} }
    func nextPrayer()->String { let now=Date(); var cal=Calendar(identifier:.gregorian); cal.timeZone=TimeZone(identifier:campus.timezone)!; let names=[("Fajr",campus.iqamah.fajr),("Dhuhr",campus.iqamah.dhuhr),("Asr",campus.iqamah.asr),("Maghrib",campus.iqamah.maghrib),("Isha",campus.iqamah.isha)]; let comps=cal.dateComponents([.year,.month,.day],from:now); for item in names { let p=item.1.split(separator:":").compactMap{Int($0)}; if p.count == 2, let date=cal.date(from:DateComponents(year:comps.year,month:comps.month,day:comps.day,hour:p[0],minute:p[1])), date > now { return "Next prayer: \(item.0)" } }; return "Next prayer: Fajr tomorrow" }
}
struct ScheduleCard: View { let campus:Campus; var body:some View { VStack(alignment:.leading,spacing:10){Text("Prayer times").font(.headline).foregroundStyle(.forest); if let row=campus.timetable.first { ForEach([(String("Fajr"),row.fajr),("Sunrise",row.sunrise),("Dhuhr",row.dhuhr),("Asr",row.asr),("Maghrib",row.maghrib),("Isha",row.isha)],id:\.0){r in HStack{Text(r.0);Spacer();Text(r.1).monospacedDigit();Text(iqamah(for:r.0)).foregroundStyle(.brass).font(.caption)}} } }.cardStyle() }
    func iqamah(for name:String)->String { switch name {case "Fajr":campus.iqamah.fajr;case "Dhuhr":campus.iqamah.dhuhr;case "Asr":campus.iqamah.asr;case "Maghrib":campus.iqamah.maghrib;case "Isha":campus.iqamah.isha;default:""} }
}
struct ContactCard: View { let campus:Campus; var body:some View { VStack(alignment:.leading,spacing:8){Text("Visit").font(.headline).foregroundStyle(.forest);Text(campus.address+", "+campus.city).foregroundStyle(.secondary);HStack{Link(destination:URL(string:"tel:\(campus.phone.filter{ $0.isNumber || $0==\"+\"})")!){Label("Call",systemImage:"phone")};Link(destination:URL(string:"mailto:\(campus.email)")!){Label("Email",systemImage:"envelope")}; if let u=mapsURL(){Link(destination:u){Label("Maps",systemImage:"map")}}}.buttonStyle(.bordered)}.cardStyle()}; func mapsURL()->URL?{var c=URLComponents(string:"https://maps.apple.com/");c?.queryItems=[URLQueryItem(name:"ll",value:"\(campus.latitude),\(campus.longitude)"),URLQueryItem(name:"q",value:campus.name)];return c?.url} }
struct EventsView: View { @EnvironmentObject var model:AppModel; var body:some View { Shell(title:"Events") { CampusPicker(); if let site=model.site,let id=model.campus?.id { ForEach(getCampusEvents(site,campusId:id)){event in NavigationLink { Shell(title:event.title) { Text(event.description).foregroundStyle(.forest); Label(event.location,systemImage:"mappin.and.ellipse").foregroundStyle(.secondary); Text(event.startsAt).font(.caption).foregroundStyle(.secondary) } } label: { VStack(alignment:.leading,spacing:6){Text(event.category.uppercased()).font(.caption.weight(.bold)).foregroundStyle(.brass);Text(event.title).font(.title3.bold()).foregroundStyle(.forest);Text(event.location).font(.caption).foregroundStyle(.secondary)}.cardStyle() } } } } } }
struct AnnouncementsView: View { @EnvironmentObject var model:AppModel; var body:some View { Shell(title:"Updates") { CampusPicker(); if let site=model.site,let id=model.campus?.id { ForEach(getCampusAnnouncements(site,campusId:id)){a in NavigationLink{AnnouncementDetail(announcement:a)}label:{VStack(alignment:.leading){Text(a.title).font(.headline).foregroundStyle(.forest);Text(a.body).lineLimit(2).foregroundStyle(.secondary)}}.cardStyle()} } } } }
struct AnnouncementDetail: View { let announcement:Announcement; var body:some View { Shell(title:announcement.title){Text(announcement.body).font(.body).foregroundStyle(.forest)} } }
struct SettingsView: View { @EnvironmentObject var model:AppModel; var body:some View { Shell(title:"Settings") { VStack(alignment:.leading,spacing:12){Text("Website base").font(.headline);TextField("https://example.org",text:$model.websiteBase).textInputAutocapitalization(.never).keyboardType(.URL).textFieldStyle(.roundedBorder);Button("Refresh site data",action:model.refresh).buttonStyle(.borderedProminent).tint(.forest);Text("The app fetches data/v1/site.json over HTTPS and keeps the last valid copy for offline use.").font(.footnote).foregroundStyle(.secondary); if case .failed(let message)=model.status {Notice(text:message,icon:"exclamationmark.triangle")} }.cardStyle(); if let org=model.site?.organization { VStack(alignment:.leading){Text(org.name).font(.headline);Text(org.tagline).foregroundStyle(.secondary)}.cardStyle() } } } }
struct Notice:View{let text:String;let icon:String;var body:some View{Label(text,systemImage:icon).font(.footnote).foregroundStyle(.brass).padding(12).frame(maxWidth:.infinity,alignment:.leading).background(Color.brass.opacity(0.12)).clipShape(RoundedRectangle(cornerRadius:12))}}
extension View { func cardStyle()->some View { self.padding(16).frame(maxWidth:.infinity,alignment:.leading).background(Color.white.opacity(0.72),in:RoundedRectangle(cornerRadius:18)).overlay{RoundedRectangle(cornerRadius:18).stroke(Color.brass.opacity(0.15))} } }
extension Color { static let ivory=Color(red:0.965,green:0.953,blue:0.925);static let forest=Color(red:0.094,green:0.235,blue:0.204);static let brass=Color(red:0.651,green:0.486,blue:0.263) }
