import Foundation

public enum SiteError: Error, Equatable, LocalizedError { case invalid(String); public var errorDescription: String? { if case .invalid(let s) = self { return s }; return nil } }

private func strict<T: CodingKey>(_ c: KeyedDecodingContainer<T>, _ allowed: Set<String>) throws { let unknown = Set(c.allKeys.map { $0.stringValue }).subtracting(allowed); if let key = unknown.first { throw SiteError.invalid("Unknown field: \(key)") } }
private func validText(_ value: String, _ max: Int) -> Bool { !value.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty && value.utf16.count <= max }
private func validID(_ value: String) -> Bool { value.range(of: "^[a-z0-9]+(?:-[a-z0-9]+)*$", options: .regularExpression) != nil && value.utf16.count <= 64 }
private func validTime(_ value: String) -> Bool { value.range(of: "^(?:[01][0-9]|2[0-3]):[0-5][0-9]$", options: .regularExpression) != nil }
private func validDate(_ value: String) -> Bool {
    guard value.range(of: "^\\d{4}-\\d{2}-\\d{2}$", options: .regularExpression) != nil else { return false }
    let parts = value.split(separator: "-").compactMap { Int($0) }
    guard parts.count == 3 else { return false }
    var calendar = Calendar(identifier: .gregorian); calendar.timeZone = TimeZone(secondsFromGMT: 0)!
    let components = DateComponents(calendar: calendar, timeZone: calendar.timeZone, year: parts[0], month: parts[1], day: parts[2])
    guard let date = calendar.date(from: components) else { return false }
    return parts[0] >= 1900 && parts[0] <= 2200 && calendar.dateComponents([.year, .month, .day], from: date).year == parts[0] && calendar.dateComponents([.year, .month, .day], from: date).month == parts[1] && calendar.dateComponents([.year, .month, .day], from: date).day == parts[2]
}
private func validTimestamp(_ value: String) -> Bool {
    guard value.utf16.count <= 40, value.range(of: "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?(?:Z|[+-]\\d{2}:\\d{2})$", options: .regularExpression) != nil else { return false }
    return validDate(String(value.prefix(10))) && ISO8601DateFormatter().date(from: value) != nil
}
private func validURL(_ value: String, allowPath: Bool = false) -> Bool {
    if allowPath && !value.contains("://") {
        return value.utf16.count <= 512 && !value.isEmpty && !value.contains("..") && value.range(of: "^/?[A-Za-z0-9_-]+(?:/[A-Za-z0-9_-]+)*\\.(?:svg|png|webp|jpg|jpeg|avif)$", options: [.regularExpression, .caseInsensitive]) != nil
    }
    guard value.utf16.count <= 2048, !value.contains(where: { $0.isWhitespace || $0 == "\\" }), let u = URL(string: value), u.scheme?.lowercased() == "https", u.host != nil, u.user == nil, u.password == nil else { return false }
    return true
}
private func validHex(_ value: String) -> Bool { value.range(of: "^#[0-9A-Fa-f]{6}$", options: .regularExpression) != nil }
private func validEmail(_ value: String) -> Bool { value.utf16.count <= 254 && value.range(of: "^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$", options: .regularExpression) != nil }
private func validAssetPath(_ value: String) -> Bool { value.range(of: "^/?[A-Za-z0-9_-]+(?:/[A-Za-z0-9_-]+)*\\.(?:svg|png|webp|jpg|jpeg|avif)$", options: [.regularExpression, .caseInsensitive]) != nil }

public struct Theme: Codable, Equatable { public let accent, background: String; public init(accent: String, background: String) { self.accent = accent; self.background = background }; enum K: String, CodingKey { case accent, background }; public init(from d: Decoder) throws { let c = try d.container(keyedBy: K.self); try strict(c,["accent","background"]); accent = try c.decode(String.self,forKey:.accent); background = try c.decode(String.self,forKey:.background) } }
public struct Organization: Codable, Equatable { public let name, tagline, description, email, phone, website, logo: String; public let theme: Theme; enum K: String,CodingKey { case name,tagline,description,email,phone,website,logo,theme }; public init(from d: Decoder)throws{let c=try d.container(keyedBy:K.self);try strict(c,Set(K.allCases.map{$0.rawValue}));name=try c.decode(String.self,forKey:.name);tagline=try c.decode(String.self,forKey:.tagline);description=try c.decode(String.self,forKey:.description);email=try c.decode(String.self,forKey:.email);phone=try c.decode(String.self,forKey:.phone);website=try c.decode(String.self,forKey:.website);logo=try c.decode(String.self,forKey:.logo);theme=try c.decode(Theme.self,forKey:.theme)} }
public struct Calculation: Codable, Equatable { public let method, madhab: String; enum K:String,CodingKey{case method,madhab}; public init(method:String,madhab:String){self.method=method;self.madhab=madhab}; public init(from d:Decoder)throws{let c=try d.container(keyedBy:K.self);try strict(c,["method","madhab"]);method=try c.decode(String.self,forKey:.method);madhab=try c.decode(String.self,forKey:.madhab)} }
public struct Iqamah: Codable, Equatable { public let fajr,dhuhr,asr,maghrib,isha:String; enum K:String,CodingKey{case fajr,dhuhr,asr,maghrib,isha}; public init(fajr:String,dhuhr:String,asr:String,maghrib:String,isha:String){self.fajr=fajr;self.dhuhr=dhuhr;self.asr=asr;self.maghrib=maghrib;self.isha=isha}; public init(from d:Decoder)throws{let c=try d.container(keyedBy:K.self);try strict(c,Set(K.allCases.map{$0.rawValue}));fajr=try c.decode(String.self,forKey:.fajr);dhuhr=try c.decode(String.self,forKey:.dhuhr);asr=try c.decode(String.self,forKey:.asr);maghrib=try c.decode(String.self,forKey:.maghrib);isha=try c.decode(String.self,forKey:.isha)} }
public struct Jumuah: Codable, Equatable { public let label,time:String; enum K:String,CodingKey{case label,time}; public init(label:String,time:String){self.label=label;self.time=time}; public init(from d:Decoder)throws{let c=try d.container(keyedBy:K.self);try strict(c,["label","time"]);label=try c.decode(String.self,forKey:.label);time=try c.decode(String.self,forKey:.time)} }
public struct PrayerDay: Codable, Equatable { public let date,fajr,sunrise,dhuhr,asr,maghrib,isha:String; public let iqamah:Iqamah?; public let source:String?; enum K:String,CodingKey{case date,fajr,sunrise,dhuhr,asr,maghrib,isha,iqamah,source}; public init(from d:Decoder)throws{let c=try d.container(keyedBy:K.self);try strict(c,Set(K.allCases.map{$0.rawValue}));date=try c.decode(String.self,forKey:.date);fajr=try c.decode(String.self,forKey:.fajr);sunrise=try c.decode(String.self,forKey:.sunrise);dhuhr=try c.decode(String.self,forKey:.dhuhr);asr=try c.decode(String.self,forKey:.asr);maghrib=try c.decode(String.self,forKey:.maghrib);isha=try c.decode(String.self,forKey:.isha);iqamah=try c.decodeIfPresent(Iqamah.self,forKey:.iqamah);source=try c.decodeIfPresent(String.self,forKey:.source)} }
public struct Campus: Codable, Equatable, Identifiable { public let id,name,address,city,timezone,phone,email:String; public let latitude,longitude:Double; public let facilities:[String]; public let calculation:Calculation; public let iqamah:Iqamah; public let jumuah:[Jumuah]; public let timetable:[PrayerDay]; enum K:String,CodingKey{case id,name,address,city,timezone,latitude,longitude,phone,email,facilities,calculation,iqamah,jumuah,timetable}; public init(from d:Decoder)throws{let c=try d.container(keyedBy:K.self);try strict(c,Set(K.allCases.map{$0.rawValue}));id=try c.decode(String.self,forKey:.id);name=try c.decode(String.self,forKey:.name);address=try c.decode(String.self,forKey:.address);city=try c.decode(String.self,forKey:.city);timezone=try c.decode(String.self,forKey:.timezone);latitude=try c.decode(Double.self,forKey:.latitude);longitude=try c.decode(Double.self,forKey:.longitude);phone=try c.decode(String.self,forKey:.phone);email=try c.decode(String.self,forKey:.email);facilities=try c.decode([String].self,forKey:.facilities);calculation=try c.decode(Calculation.self,forKey:.calculation);iqamah=try c.decode(Iqamah.self,forKey:.iqamah);jumuah=try c.decode([Jumuah].self,forKey:.jumuah);timetable=try c.decode([PrayerDay].self,forKey:.timetable)} }
public struct Event: Codable, Equatable, Identifiable { public let id,title,description,startsAt,endsAt:String; public let campusIds:[String]; public let location,category:String; enum K:String,CodingKey{case id,title,description,startsAt,endsAt,campusIds,location,category}; public init(from d:Decoder)throws{let c=try d.container(keyedBy:K.self);try strict(c,Set(K.allCases.map{$0.rawValue}));id=try c.decode(String.self,forKey:.id);title=try c.decode(String.self,forKey:.title);description=try c.decode(String.self,forKey:.description);startsAt=try c.decode(String.self,forKey:.startsAt);endsAt=try c.decode(String.self,forKey:.endsAt);campusIds=try c.decode([String].self,forKey:.campusIds);location=try c.decode(String.self,forKey:.location);category=try c.decode(String.self,forKey:.category)} }
public struct Announcement: Codable, Equatable, Identifiable { public let id,title,body,publishedAt:String; public let campusIds:[String]; public let expiresAt:String?; enum K:String,CodingKey{case id,title,body,campusIds,publishedAt,expiresAt}; public init(from d:Decoder)throws{let c=try d.container(keyedBy:K.self);try strict(c,Set(K.allCases.map{$0.rawValue}));id=try c.decode(String.self,forKey:.id);title=try c.decode(String.self,forKey:.title);body=try c.decode(String.self,forKey:.body);campusIds=try c.decode([String].self,forKey:.campusIds);publishedAt=try c.decode(String.self,forKey:.publishedAt);expiresAt=try c.decodeIfPresent(String.self,forKey:.expiresAt)} }
private func timestampDate(_ value: String) -> Date? { ISO8601DateFormatter().date(from:value) }
public struct Site: Codable, Equatable { public let schemaVersion:Int; public let updatedAt:String; public let organization:Organization; public let campuses:[Campus]; public let events:[Event]; public let announcements:[Announcement]; enum K:String,CodingKey{case schemaVersion,updatedAt,organization,campuses,events,announcements}; public init(from d:Decoder)throws{let c=try d.container(keyedBy:K.self);try strict(c,Set(K.allCases.map{$0.rawValue}));schemaVersion=try c.decode(Int.self,forKey:.schemaVersion);updatedAt=try c.decode(String.self,forKey:.updatedAt);organization=try c.decode(Organization.self,forKey:.organization);campuses=try c.decode([Campus].self,forKey:.campuses);events=try c.decode([Event].self,forKey:.events);announcements=try c.decode([Announcement].self,forKey:.announcements);try validate()}
 public func validate() throws {
  guard schemaVersion == 1, validTimestamp(updatedAt), !campuses.isEmpty, campuses.count <= 20, events.count <= 500, announcements.count <= 500 else { throw SiteError.invalid("site metadata or array bounds") }
  guard validText(organization.name, 200), validText(organization.tagline, 300), validText(organization.description, 20000), validEmail(organization.email), validText(organization.phone, 40), validURL(organization.website), (organization.logo.contains("://") ? validURL(organization.logo) : validURL(organization.logo, allowPath: true)), validHex(organization.theme.accent), validHex(organization.theme.background) else { throw SiteError.invalid("organization fields") }
  let ids=campuses.map(\.id); guard Set(ids).count == ids.count, ids.allSatisfy(validID) else { throw SiteError.invalid("campus IDs") }
  for c in campuses {
   guard validText(c.name,160), validText(c.address,500), validText(c.city,120), validText(c.timezone,100), validText(c.phone,40), validEmail(c.email), c.facilities.count <= 40, c.facilities.allSatisfy({ validText($0,100) }), c.jumuah.count <= 10, c.timetable.count <= 1500, ["NorthAmerica","MuslimWorldLeague","Egyptian","Karachi","UmmAlQura","Dubai","MoonsightingCommittee"].contains(c.calculation.method), ["Shafi","Hanafi"].contains(c.calculation.madhab), TimeZone(identifier:c.timezone) != nil, c.latitude >= -90 && c.latitude <= 90, c.longitude >= -180 && c.longitude <= 180 else { throw SiteError.invalid("campus \(c.id)") }
   var dates=Set<String>(); for p in c.timetable { guard dates.insert(p.date).inserted, validDate(p.date), [p.fajr,p.sunrise,p.dhuhr,p.asr,p.maghrib,p.isha].allSatisfy(validTime) else { throw SiteError.invalid("prayer row") }; if let source=p.source, source != "calculated" && source != "uploaded" { throw SiteError.invalid("source") }; if let i=p.iqamah, ![i.fajr,i.dhuhr,i.asr,i.maghrib,i.isha].allSatisfy(validTime) { throw SiteError.invalid("prayer iqamah") } }
  guard c.jumuah.allSatisfy({ validText($0.label,100) && validTime($0.time) }), [c.iqamah.fajr,c.iqamah.dhuhr,c.iqamah.asr,c.iqamah.maghrib,c.iqamah.isha].allSatisfy(validTime) else { throw SiteError.invalid("schedule") }
  }
  var eventIDs=Set<String>(); for e in events { guard eventIDs.insert(e.id).inserted, validID(e.id), validText(e.title,200), validText(e.description,10000), validText(e.location,300), validText(e.category,80), validTimestamp(e.startsAt), validTimestamp(e.endsAt), e.campusIds.count <= 20, Set(e.campusIds).count == e.campusIds.count, e.campusIds.allSatisfy({ validID($0) && ids.contains($0) }), let start=timestampDate(e.startsAt), let end=timestampDate(e.endsAt), end > start else { throw SiteError.invalid("event") } }
  var announcementIDs=Set<String>(); for a in announcements { guard announcementIDs.insert(a.id).inserted, validID(a.id), validText(a.title,200), validText(a.body,10000), a.campusIds.count <= 20, Set(a.campusIds).count == a.campusIds.count, a.campusIds.allSatisfy({ validID($0) && ids.contains($0) }), validTimestamp(a.publishedAt), a.expiresAt == nil || validTimestamp(a.expiresAt!), let published=timestampDate(a.publishedAt), a.expiresAt == nil || timestampDate(a.expiresAt!)! > published else { throw SiteError.invalid("announcement") } }
 }
}
private extension DateFormatter { static let rfc3339: DateFormatter = { let f=DateFormatter();f.locale=Locale(identifier:"en_US_POSIX");f.dateFormat="yyyy-MM-dd'T'HH:mm:ssXXXXX";return f }() }
public func localDateISO(_ now: Date, timeZone: TimeZone) -> String { var cal=Calendar(identifier:.gregorian);cal.timeZone=timeZone;let c=cal.dateComponents([.year,.month,.day],from:now);return String(format:"%04d-%02d-%02d",c.year!,c.month!,c.day!) }
public func getPrayerDay(_ site: Site, campusId: String, dateISO: String) -> PrayerDay? { site.campuses.first{$0.id==campusId}?.timetable.first{$0.date==dateISO} }
public func getCampusEvents(_ site: Site, campusId: String) -> [Event] { site.events.filter{$0.campusIds.isEmpty || $0.campusIds.contains(campusId)}.sorted{$0.startsAt<$1.startsAt} }
public func getCampusAnnouncements(_ site: Site, campusId: String) -> [Announcement] { site.announcements.filter{$0.campusIds.isEmpty || $0.campusIds.contains(campusId)}.sorted{$0.publishedAt>$1.publishedAt} }
